spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        ddl-auto: update
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    enabled: true
    change-log: db/master-changelog.xml
    default-schema: public
server:
  port: 8083