spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        ddl-auto: update
        show_sql: true
        temp:
          use_jdbc_metadata_defaults: false
  liquibase:
    enabled: true
    change-log: db/master-changelog.xml
    default-schema: public
  rabbitmq:
    host: 127.0.0.1
    password: guest
    username: guest
    port: 5672

server:
  port: 8083

logging:
  pattern:
    file: "%d{ISO8601} [%thread] [%-5level] Class [%class{50}] Method: [%method] on line %line : %msg%n  %ex{full}"
    rolling-file-name: log/Person-service-%d{yyyy-MM-dd}.%i.log
  level:
    root: info
    org.springframework.web: ERROR
    org.hibernate: ERROR
  file:
    max-size: 10MB
    total-size-cap: 100MB
    max-history: 30
    clean-history-on-start: true
    name: log/Person-service-logs.log
